[package]
name = "btree"
version = "0.1.0"
authors = ["nshneor <nshneor@redhat.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.4"
uuid = { version = "1.5.0", features = ["serde", "v4", "fast-rng"] }
memmap = "0.7.0"
